ifndef::env-github[:icons: font]
:toc: preamble
:toclevels: 2
:sectanchors:
:description: A D-lang GUI for Bitwarden
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:

ifdef::env-github[]
++++
<a id="readme-top"></a>
<div align="center">
<a href="https://github.com/AMDphreak/d-warden/graphs/contributors"><img src="https://img.shields.io/github/contributors/AMDphreak/d-warden.svg?style=for-the-badge" alt="Contributors"></a>
<a href="https://github.com/AMDphreak/d-warden/network/members"><img src="https://img.shields.io/github/forks/AMDphreak/d-warden.svg?style=for-the-badge" alt="Forks"></a>
<a href="https://github.com/AMDphreak/d-warden/stargazers"><img src="https://img.shields.io/github/stars/AMDphreak/d-warden.svg?style=for-the-badge" alt="Stars"></a>
<a href="https://github.com/AMDphreak/d-warden/issues"><img src="https://img.shields.io/github/issues/AMDphreak/d-warden.svg?style=for-the-badge" alt="Issues"></a>
<br />
<h3 align="center">D-Warden</h3>
<p align="center">
A modern, cross-platform GUI client for Bitwarden built with the D programming language.<br />
<a href="https://github.com/AMDphreak/d-warden/issues">Report Bug</a>
&middot;
<a href="https://github.com/AMDphreak/d-warden/issues">Request Feature</a>
</p>
</div>
++++
endif::[]

ifndef::env-github[]
image:https://img.shields.io/github/contributors/AMDphreak/d-warden.svg?style=for-the-badge[Contributors,link=https://github.com/AMDphreak/d-warden/graphs/contributors]
image:https://img.shields.io/github/forks/AMDphreak/d-warden.svg?style=for-the-badge[Forks,link=https://github.com/AMDphreak/d-warden/network/members]
image:https://img.shields.io/github/stars/AMDphreak/d-warden.svg?style=for-the-badge[Stars,link=https://github.com/AMDphreak/d-warden/stargazers]
image:https://img.shields.io/github/issues/AMDphreak/d-warden.svg?style=for-the-badge[Issues,link=https://github.com/AMDphreak/d-warden/issues]

= D-Warden

A modern, cross-platform GUI client for Bitwarden built with the D programming language.

link:https://github.com/AMDphreak/d-warden/issues[Report Bug] ·
link:https://github.com/AMDphreak/d-warden/issues[Request Feature]
endif::[]


== About The Project

D-Warden is a modern, cross-platform GUI client for Bitwarden built with the D programming language.

link:#readme-top[back to top]

== Features

* [ ] Secure vault access
* [ ] Item management
* [ ] Password generation
* [ ] Cross-platform support

link:#readme-top[back to top]

== Installation

=== Packaging

The app's installer is configured to optimize Start Menu search. By using tokenized descriptions, users can find the app using keywords like "bit", "warden", and "password" without conflicting with other "bitwarden" results.

Refer to `installer/setup.iss` for the Inno Setup configuration.

=== Prerequisites

* D compiler (DMD, LDC, or GDC)
* DUB (package manager)

link:#readme-top[back to top]

== Usage

Documentation is managed using Antora and can be found in the `docs/` folder.

link:#readme-top[back to top]

== License

See the repository for license terms.

link:#readme-top[back to top]

== Contact

Ryan Johnson — link:https://twitter.com/amdphreak[@amdphreak]

* Project: https://github.com/AMDphreak/d-warden
* Site: https://ryanjohnson.dev

link:#readme-top[back to top]
